---
title: Poster library
date: last-modified
---

This site is home to a project to create a Quarto poster template for VCU Engineering capstone and other projects.  

## VISION

My vision is a [poster template](./assets/CS%2024-313_Poster.pdf) customized for VCU Capstone projects,
easily customizable for other VCU-related activities.  This poster template
would use the VCU Brand Standard fonts and colors, and implement a pleasing
and easily modifiable format.

The user creates a QMD file using a text editor (VS code?),
modify the YAML header, then add their content to the QMD. Stylings, layout
and formatting is left to the template styles.

We've got a starting point - an [example Quarto typst poster](./showcase-2024-10-31/showcase-2024-10-31.pdf).

Modifications to this starting point can take one of two forms:

1. A YAML header for a QMD file that contains all the necessary font, color, icon, background and other settings.  This is the preferred approach.

2. A true quarto extension that contains all the necessary files, etc., ready for use.  This is a more complicated approach, but might be useful if there are lots of options and built-in icons, images and/or logos.


This project may be a simple as reading the documentation and adding the necessary commands to the YAML header.  But, if the extension is not documented well, it make take more effort.

## Samples

The link below provide an example of what we're starting with (a template Quarto poster) and our desired product - an easily usable 

* [Sample Typst Poster](./showcase-2024-10-31/showcase-2024-10-31.pdf) - a sample poster created using the quarto typst poster format. It definitely needs work
to use VCU colors, fonts, and other features to make RAM-alicious!

Below are posters from the 2024 capstone expo.  Note the consistent use of headers, footers, colors, logos, and all that other stuff that make these posters look related to each other.  These were created using powerpoint and required lots of manual layout.  

* [CS-24-313](./assets/CS%2024-313_Poster.pdf) - Example poster from Capstone project CS-24-313, Pumphouse Machinery AR Implementation.

* [CS-24-333](./assets/CS%2024-333_Poster.pdf) - Example poster from Capstone project CS-24-333, Implementation of a STEMM

* [Other Projects](https://egr.vcu.edu/capstone/current-projects/) - An index of all projects from 2023-24 capstone projects. Each project provides a PDF abstract and a PDF poster. SCROLL DOWN, the list starts in the middle of the file.

## References

These references can help guide development of the template.

* [VCU Brand Standards](https://brand.vcu.edu/) - *Requires VCU login credentials to see all the goodies!*

* [VCU Capstone Guidelines](https://egr.vcu.edu/research/research-showcase/) - April 2024 guidelines and instructions

* [Quarto typst formats](https://quarto.org/docs/output-formats/typst-custom.html) - including the poster format.

* [Quarto typst basics](https://quarto.org/docs/output-formats/typst.html)

* [Quarto extensions](https://quarto.org/docs/extensions/)

* [Building extensions](https://quarto.org/docs/extensions/creating.html) - how to build quarto extensions

